id: P2C5765D2
initial_creation_type: input
source_metadata:
  title: Dezhung Tulku Jamyang Kunga Tenpe Gyaltsen
  parent: 2. Collected works
  source: https://sakyalibrary.com
  bases:
    8a8d:
      title: བསྟོད་ཚོགས་ནོར་བུའི་ཕྲེང་བ།
      author: སྡེ་གཞུང་སྤྲུལ་སྐུ་འཇམ་དབྱངས་ཀུན་དགའ་བསྟན་པའི་རྒྱལ་མཚན།
      base_file: 8a8d.txt
      order: 1
    25f7:
      title: བླ་མ་རྒྱང་འབོད་དང་གསོལ་འདེབས་སྐོར།
      author: སྡེ་གཞུང་སྤྲུལ་སྐུ་འཇམ་དབྱངས་ཀུན་དགའ་བསྟན་པའི་རྒྱལ་མཚན།
      base_file: 25f7.txt
      order: 2
    46be:
      title: རྗེ་བླ་མ་རྡོ་རྗེ་འཆང་ངག་དབང་ཀུན་དགའ་ལེགས་པའི་འབྱུང་གནས་ཡེ་ཤེས་རྒྱལ་མཚན་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་ངོ་མཚར་ནོར་བུའི་ཕྲེང་བ།
      author: སྡེ་གཞུང་སྤྲུལ་སྐུ་འཇམ་དབྱངས་ཀུན་དགའ་བསྟན་པའི་རྒྱལ་མཚན།
      base_file: 46be.txt
      order: 3
    7d66:
      title: ཐེག་པ་ཆེན་པོའི་བློ་སྦྱོང་གི་སྨོན་ལམ་བྱང་ཆུབ་ལམ་བཟང་།
      author: སྡེ་གཞུང་སྤྲུལ་སྐུ་འཇམ་དབྱངས་ཀུན་དགའ་བསྟན་པའི་རྒྱལ་མཚན།
      base_file: 7d66.txt
      order: 4
    c0a1:
      title: མངའ་གསོལ་འདོད་དགུའི་དཔལ་སྟེར།
      author: སྡེ་གཞུང་སྤྲུལ་སྐུ་འཇམ་དབྱངས་ཀུན་དགའ་བསྟན་པའི་རྒྱལ་མཚན།
      base_file: c0a1.txt
      order: 5
    da4a:
      title: འདུལ་བའི་ལག་ལེན་རིན་ཆེན་སྒྲོན་མེ།
      author: སྡེ་གཞུང་སྤྲུལ་སྐུ་འཇམ་དབྱངས་ཀུན་དགའ་བསྟན་པའི་རྒྱལ་མཚན།
      base_file: da4a.txt
      order: 6
    576e:
      title: སྐྱེས་མཆོག་རྣམས་ལ་གདམས་པའི་སྐོར།
      author: སྡེ་གཞུང་སྤྲུལ་སྐུ་འཇམ་དབྱངས་ཀུན་དགའ་བསྟན་པའི་རྒྱལ་མཚན།
      base_file: 576e.txt
      order: 7
    d73d:
      title: སྡེ་གཞུང་སྤྲུལ་སྐུ་རིན་པོ་ཆེ་ཀུན་དགའ་རྒྱལ་མཚན་གྱི་ཁུ་བོ་སྙན་གྲགས་ལུང་རིགས་ཉི་མའི་གསུང་།
      author: སྡེ་གཞུང་སྤྲུལ་སྐུ་འཇམ་དབྱངས་ཀུན་དགའ་བསྟན་པའི་རྒྱལ་མཚན།
      base_file: d73d.txt
      order: 8
created_at: '2022-04-06T17:10:30.932877'
last_modified_at: '2022-04-06T17:10:30.932904'
